{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "77d9312d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import jieba\n",
    "import re\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1db88ff3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. 合并训练数据\n",
    "categories = ['政治', '经济', '军事', '社会', '文化', '科技', '体育']\n",
    "dfs = []\n",
    "for cat in categories:\n",
    "    df = pd.read_csv(f'{cat}train.csv')\n",
    "    dfs.append(df)\n",
    "full_data = pd.concat(dfs, ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a83093f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Building prefix dict from the default dictionary ...\n",
      "Loading model from cache /var/folders/kk/ylyfvmrj6zv853wrvp3s_0180000gn/T/jieba.cache\n",
      "Loading model cost 0.330 seconds.\n",
      "Prefix dict has been built successfully.\n"
     ]
    }
   ],
   "source": [
    "# 2. 中文文本预处理\n",
    "def chinese_text_processing(text):\n",
    "    text = re.sub(r'[^\\u4e00-\\u9fa5]', '', str(text))  # 去除非汉字字符\n",
    "    words = jieba.cut(text)                           # 结巴分词\n",
    "    return ' '.join([w for w in words if w.strip()])   # 去除空格\n",
    "\n",
    "full_data['processed'] = full_data['Content'].apply(chinese_text_processing)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c0257df9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. 特征提取\n",
    "tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,2))\n",
    "X = tfidf.fit_transform(full_data['processed'])\n",
    "y = full_data['Area']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ce07d414",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import cross_validate\n",
    "from sklearn.metrics import make_scorer, accuracy_score, f1_score, precision_score, recall_score, roc_auc_score\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b62af2db",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 定义评估指标\n",
    "scoring = {\n",
    "    'accuracy': 'accuracy',\n",
    "    'f1_macro': 'f1_macro',\n",
    "    'precision_macro': 'precision_macro',\n",
    "    'recall_macro': 'recall_macro',\n",
    "    'roc_auc_ovr': make_scorer(roc_auc_score, needs_proba=True, multi_class='ovr')\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "701362f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.naive_bayes import MultinomialNB"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "9d4f5759",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 定义分类模型\n",
    "models = {\n",
    "    'LogisticRegression': LogisticRegression(max_iter=1000),\n",
    "    'SVM': SVC(probability=True),\n",
    "    'RandomForest': RandomForestClassifier(),\n",
    "    'NaiveBayes': MultinomialNB(),\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "522c881e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 140, in __call__\n",
      "    score = scorer._score(\n",
      "            ^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_scorer.py\", line 388, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/site-packages/sklearn/utils/_param_validation.py\", line 194, in wrapper\n",
      "    params = func_sig.bind(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3212, in bind\n",
      "    return self._bind(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/canoe/anaconda3/lib/python3.11/inspect.py\", line 3201, in _bind\n",
      "    raise TypeError(\n",
      "TypeError: got an unexpected keyword argument 'needs_proba'\n",
      "\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "# 交叉验证评估\n",
    "results = []\n",
    "for name, model in models.items():\n",
    "    cv_results = cross_validate(model, X, y, cv=5, scoring=scoring)\n",
    "    metrics = {\n",
    "        'Model': name,\n",
    "        'Accuracy': np.mean(cv_results['test_accuracy']),\n",
    "        'F1': np.mean(cv_results['test_f1_macro']),\n",
    "        'Precision': np.mean(cv_results['test_precision_macro']),\n",
    "        'Recall': np.mean(cv_results['test_recall_macro']),\n",
    "        'ROC_AUC': np.mean(cv_results['test_roc_auc_ovr'])\n",
    "    }\n",
    "    results.append(metrics)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "24270372",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 输出评估报告\n",
    "pd.DataFrame(results).to_csv('model_evaluation.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8345eda",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
